# Copyright 2018 Peter K. G. Williams and collaborators
# Licensed under the MIT License

language: rust

cache: cargo

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      rust: stable
    - os: linux
      sudo: required
      dist: xenial
      rust: beta
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libslurm-dev
      - libslurmdb-dev

env:
  - SLURM_LIBDIR=/usr/lib/x86_64-linux-gnu
  - SLURM_INCDIR=/usr/include

script:
  - |
    cargo build --verbose &&
    cargo test
