# Copyright 2017 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT licene.

[package]
name = "slurm"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"

[workspace]

[dependencies]
slurm-sys = { path = "slurm-sys" }

