# Copyright 2017-2018 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT licene.

[package]
name = "slurm"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"

[workspace]

[dependencies]
clap = "2.30"
failure = "0.1"
slurm-sys = { path = "slurm-sys" }

