# Copyright 2017 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "slurm-sys"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]
links = "slurm"
build = "build.rs"
license = "MIT"

[build-dependencies]
bindgen = "0.33"
pkg-config = "^0.3"
